# Generated by Django 5.1.7 on 2025-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('pack_size_label', models.CharField(max_length=255)),
                ('salt_composition', models.TextField()),
                ('medicine_desc', models.TextField()),
                ('substitute0', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute1', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute2', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute3', models.CharField(blank=True, max_length=255, null=True)),
                ('substitute4', models.CharField(blank=True, max_length=255, null=True)),
                ('habit_forming', models.CharField(max_length=50)),
                ('therapeutic_class', models.CharField(max_length=255)),
                ('use0', models.TextField()),
                ('side_effects', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
            ],
        ),
    ]
