# Generated by Django 5.1.7 on 2025-04-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
    ]
